### ISSUE TITLE
TEdit4-Beta 20 for Terraria 1.4

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#1182]
# Running release notes for 1.4

## This is BETA, use for testing and helping locate bugs and trying out new features.

Thank you all for testing, feedback and pull requests. All of the information will help this project move forward. This release should be functional and save files should not be broken. Numerous bug and crash fixes have been resolved for some long standing issues. 

What's left? Check out the milestone for Journey's End: https://github.com/TEdit/Terraria-Map-Editor/milestone/10

## Download
- https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta20
  - Signed with cert thumbprint `90d6d0efe6ca5c025679f499a72d773721a259d3`

## Issues 
- [ ] NPC sprite frames offset (cat, dog)
- [x] Add missing deco tiles #1283
- [x] Add a warning if world file will change version #1302
- [x] Fix missing sprites (dressers, beds, chests) #1311 
- [x] Fix chest type not displaying for new chests #1310 
- [x] Fix find chest plugin not searching ALL chests #1310 
- [x] Fix Copy/paste of new sprites  #1311 
- [x] Fix FlipX FlipY on clipboard for sprites, should work with unknown sprites now. #1311 
- [x] Many sprite fixes
- [x] (Work in progress) More visibility in new sprite picker 
- [x] T - Sprite hotkey and Ctrl+D - Deselect area should work #1277
- [x] Fix "Find Chest" plugin crash #1288
- [x] Shift + Arrow keys for faster scrolling
- [x] Show paint colors. #454
- [x] Add a selection size box and color it yellow if selection is active. This should help with not knowing if you have a selected region #1272
- [x] Mouse wheel zooming locks on to cursor, should behave smoother #1274 #919 
- [x] Sprite tool fix combobox being hard to select #1275
- [x] Add option for code signing.
- [x] Fix byte cast for wall data. Closes #1252
- [x] Add version check for DeserializeTileData
- [x] Add shortcuts for tile/wall toggle. Fixes #1267
- [x] Add pink moon, fixes #1271
- [x] github link points to github fixes #1270
- [x] Signed with cert thumbprint `90d6d0efe6ca5c025679f499a72d773721a259d3` You can add this to your trusted certs if you have windows smartscreen issues.
- [x] fix chest limit to 8000 (was 1000)
- [x] Import Bestiary and Kill Tally from other world
- [x] Crash on clipboard FlipX FlipY 
- [x] Version check always says out of date, title bar wrong version
- [x] Tally tab causing crash
- [x] Missing Illuminant Paint causing world to not render
- [x] Editing of display doll and hat rack not working yet
- [x] 1.4 sprites do not have any variants (just the base image)
- [x] Placing container tile entities (Teleport pylon,Hat rack, Weapon Rack, display doll) does not create the storage data. #1200 #1215
- [x] 1.4.0.4 support (world file 228)
- [x] 1.4.0.3 support (world file 227)
- [x] Golfer incorrect id
- [x] No master mode
- [x] Bestiary section failed to load #1195  #1192 #1194 #1199

## Commenting
If you have _constructive feedback_, such as config file edits or something that will help speed development or improve the application please leave a comment here. Things like "it didn't work" are not meant for this thread. Thanks.

**Comment by Arthur-Kenichi-Condino** [comment]
just read this. I wanna help though. Anything I can test for you?

**Comment by tomek-i** [comment]
@BinaryConstruct  welcome back!

you should dev. Consider adding a few people to the repo to help you out :)

**Comment by BinaryConstruct** [comment]
> @BinaryConstruct welcome back!
> 
> you should dev. Consider adding a few people to the repo to help you out :)
Anyone is free to submit a PR! 


> 
> 
> just read this. I wanna help though. Anything I can test for you?
Download the beta, load worlds. Identify missing tiles, test for crashes. There will be a warning about the file footer that will be resolved with the next release. 

Tile IDs for all the new tiles > id 470 to 623 are missing from the https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/settings.xml file.

**Comment by Arthur-Kenichi-Condino** [comment]
I'm working on a project now, when I get it done, I'll try searching some more. But I have the beta here and the visual studio open. I tried to add try-catch but then the texture data in tiles has a argument null exception, if I remember right.

Will you make a World Save/Load V3? 

I'll try to list some unknown tiles and the ids the app shows with pink squares.

**Comment by theoceanmytho** [comment]
is it still possible to edit worlds for doing things like getting rid of world evils/hallow? or would that brick the world as well?

**Comment by theoceanmytho** [comment]
answered my own question, answer's no. looking forward to the next version so i can get back to getting rid of world evil and hallow

**Comment by BinaryConstruct** [comment]
Beta 2 is out, it should have functional save files.

**Comment by theoceanmytho** [comment]
lit

**Comment by Chaox666** [comment]
I tried to change the difficulty to expert mode, but there is no expert mode in the dropdown menu. Could you add it?

**Comment by theoceanmytho** [comment]
Quick question, at the end of the saving process for modified worlds, it
says "save creative powers..", what does it mean and on average for a large
world, how long does that saving process specifically take?

**Comment by nosnowowie93347** [comment]
plz fix this
![image](https://user-images.githubusercontent.com/65568190/82256733-b8a91480-990b-11ea-810a-0cbe79f146c6.png)

**Comment by nosnowowie93347** [comment]
also every time i change something and save, none of the changes are there ingame

**Comment by Roxas027** [comment]
Save function doesn't work (as well as Save as) tried to save as a new map, not working, (running with and without administrator) so it's a save problem

**Comment by nosnowowie93347** [comment]
same @Roxas027

**Comment by nosnowowie93347** [comment]
@BinaryConstruct please fix this
and sorry for @ you but I felt you need to hear this

**Comment by theoceanmytho** [comment]
I have the same problem as nosnowowie, hope this gets fixed soon

**Comment by theoceanmytho** [comment]
@nosnowowie93347  we might have the same problem, are you stuck on "Save Creative Powers..." on the saving stage and decide to leave at that point? To further specify it's only happening to me on my main world, a large classic mode world, the problem might be in world size and/or world type, since i also have a small journey mode world and that saved all the changes i put on it in tedit without any problem

**Comment by nosnowowie93347** [comment]
@theoceanmytho YES THAT IS THE PROBLEM
it's that damn saving creative powers. @BinaryConstruct THAT"S WHAT'S BREAKING THE APP
srry about caps just excited that SOMEONE else has this issue

**Comment by nosnowowie93347** [comment]
is the developer even here to see our feedback?
i hope so

**Comment by nosnowowie93347** [comment]
if this brokenness is release two, I'd hate to see release 1 xD

**Comment by theoceanmytho** [comment]
release 1 was the version where you couldnt even load save files. i'm currently setting up at least 2 different worlds to see if it's either an issue with world size or world type, i'll let you know about the results of what im doing

**Comment by theoceanmytho** [comment]
ok, i think i know the problem, but i'm only about 50% or so done with the experiment, i'll have to make 3 journey mode worlds to fully gauge how bad it is, the small classic mode world has the save creative powers problem as well, update on experiment should be soon

**Comment by theoceanmytho** [comment]
alright, there are 2 potential reasons behind the 'save creative powers' issues. The first is the world's in classic mode. The second is that the world is hard mode, i'll need to make at least 3 worlds, all journey mode, to fully verify.

**Comment by ericdallo** [comment]
@theoceanmytho I have a world in pre-hardmode of medium size in classic mode with the same "Save creative Powers..." bug

**Comment by theoceanmytho** [comment]
I'm willing to bet that the 'save creative powers' bug is caused from the classic mode, journey mode has no quarrels with loading tedit modifications (i just use the pencil tool to draw a dirt L in the sky for modifications, if there's no L, it didn't work)

**Comment by theoceanmytho** [comment]
also quick update: small journey mode world is loading up tedit mods just fine, it's pre-hardmode

**Comment by theoceanmytho** [comment]
ok i THINK i know the problem with 'save creative powers'. It's a bug caused by 2 problems, the first one and MOST common one is the world being 'classic' mode, the second mode which i had a suspect feeling about it being something that can cause the bug, is the world being in hard mode. While i haven't tried it yet with master mode that's because i'm refusing to play master mode in any capacity without doing a playthrough with friends first. but yeah, the 'Save Creative Powers..." problem is caused by classic mode for a total game mode and hard mode being enabled, one of these individually can both cause the problem. both of them at the same time cause it as well. @BinaryConstruct  @nosnowowie93347  @ericdallo  hope this helps, sorry for the ping

**Comment by Dcollins85** [comment]
@theoceanmytho I tried it in Master Mode and I get the same thing "Save Creative Powers..."

**Comment by Chibbens** [comment]
@Dcollins85 I have the same issue with Master Mode, although instead of getting stuck in "Save Creative Powers" I get stuck on "Save Bestiary".

**Comment by theoceanmytho** [comment]
Like i said in the previous post, for more personal reasons than anything i have no way to help you, i'm sorry if it seems selfish but i'd be happy to help you once i start a master mode playthrough to fully figure out the problem. Sorry again.

**Comment by Chibbens** [comment]
@theoceanmytho No worries, I'm sure the dev will patch the bug soon.

**Comment by ericdallo** [comment]
Just downloaded the source code and debugged it until found the problem, that is on reading the bestiary section @BinaryConstruct...
Well, I never worked with C# neither .net but after removing[these lines](https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/Terraria/World.FileV2.cs#L64-L65), it seems to save the world successfully :)

**Comment by ericdallo** [comment]
Remember to backup your world as I'm sure that this is not the correct way to fix the problem.
[TEdit-workaround.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4647717/TEdit-workaround.zip)

**Comment by theoceanmytho** [comment]
Odds are either tomorrow or a few days the devs' will fix it

**Comment by BinaryConstruct** [comment]
Rest assured I am reading these comments and will work on these issues. Please be patient, solving issues can take a while to track down all the edge cases. PRs are welcome, additionally you can view the source for other map editor/viewers to get ideas for how to fix bugs. These other projects are all going through the same changes.

**Comment by schrodingerspsycho** [comment]
Also - it seems that it got that problem with opening journey mode worlds, non-journey 1.4 worlds can be opened.

**Comment by Dcollins85** [comment]
@BinaryConstruct When I changed the world difficulty to Expert I got it to work. Just an FYI. I made a brand new world, didn't change the name, kept it on random for corruption/crimson, and set the world difficulty to Expert. I went in with my main character and it worked just fine. TEdit saved my changes and everything.

**Comment by theoceanmytho** [comment]
So the problem is, at the very least, something in the code for the bestiary.

**Comment by BinaryConstruct** [comment]
Beta 3 fixes bestiary. There is still the issue with special container tiles.

**Comment by nosnowowie93347** [comment]
praying that beta 3 also fixed the no saving world problem

**Comment by theoceanmytho** [comment]
since the saving problem was caused by the bestiary it's very probable, i'll check later tonight.

**Comment by theoceanmytho** [comment]
'later tonight' Came alot sooner than i thought, it works just fine now, i removed corruption where i didn't want it and added a dirt border around a pylon i placed, thanks for fixing the bug

**Comment by theoceanmytho** [comment]
P.S. The pylons' stop working when you load into a tedit-ed world, but the fix for that is to just break them and place them back where you put them

**Comment by BinaryConstruct** [comment]
> 
> 
> P.S. The pylons' stop working when you load into a tedit-ed world, but the fix for that is to just break them and place them back where you put them

This is related to #1200

**Comment by nosnowowie93347** [comment]
@theoceanmytho nice. glad saving works now

**Comment by nosnowowie93347** [comment]
does copy-paste schematics still work? god i hope so

**Comment by theoceanmytho** [comment]
havent tested it yet, i'll do it later

**Comment by nosnowowie93347** [comment]
ok

**Comment by nosnowowie93347** [comment]
no need to do it right away.

**Comment by Tenouchi** [comment]
Hello BinaryConstruct :) I just wanted to say thank you for all your hard work. I wasn't able to save my structure from my old world to my new one, but after the BETA 3 update it works! Thank you again

**Comment by MHN-Hartech** [comment]
Just tried to copy & paste a schematic. worked fine up until i tried to save where it was stuck at "Save Bestiary..."

**Comment by Chibbens** [comment]
@MHN-Hartech I had the same issue even after the patch, but I managed to fix it. There seems to be a bug involving special container tile entities, such as hat racks, weapon racks, etc., that somehow correlates to the "Save Bestiary" bug. The way I resolved it was going into the world on Terraria and removing the hat racks and other similar entities, saving and exiting the world, and then loading it up in TEdit. This managed to fix my issue.

**Comment by BinaryConstruct** [comment]
> 
> 
> @MHN-Hartech I had the same issue even after the patch, but I managed to fix it. There seems to be a bug involving special container tile entities, such as hat racks, weapon racks, etc., that somehow correlates to the "Save Bestiary" bug. The way I resolved it was going into the world on Terraria and removing the hat racks and other similar entities, saving and exiting the world, and then loading it up in TEdit. This managed to fix my issue.

This is issue #1200, the next on the To fix list.

**Comment by nosnowowie93347** [comment]
@BinaryConstruct what does the Simple Ore Generator do? I know this may not be the best place to ask, but I need to know.

**Comment by nosnowowie93347** [comment]
and yes copypaste works

**Comment by FlamingSharky** [comment]
How do I get this to run on mac? I have wine and all but I don't know what file I use to open it

**Comment by theoceanmytho** [comment]
i dont use mac so i cant help you there. sorry

**Comment by FlamingSharky** [comment]
Oh wait, sorry, just found the file lmao, ill report any bugs

**Comment by FlamingSharky** [comment]
Well, I can't run it apparently, any mac users that can help me out with this?

**Comment by nosnowowie93347** [comment]
fix this @BinaryConstruct 
![image](https://user-images.githubusercontent.com/65568190/82372971-b7dab600-99d1-11ea-8bbf-824c2cf5ee7f.png)

**Comment by nosnowowie93347** [comment]
happens when importing schematic @BinaryConstruct

**Comment by BinaryConstruct** [comment]
Could you please attach the schematic file to a new issue?

**Comment by atheran2** [comment]
While yesterday it was working fine for me, except the bug with placeable items (chests/pylons/etc) today it refuses to open the world I was playing yesterday. That happens both in beta 3 that I used yesterday and in beta 4 I just downloaded.


![](https://i.gyazo.com/f8db958280c11f1391247844b8cf632c.png)
This is the error I get and it tells me to upload this.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4656680/TEditLog.txt)

That happens with multiple worlds I was able to open and edit yesterday. Ingame I can play fine without any issues and the weird thing is that I changed nothing between my last edit yesterday and trying to open the world today.

**Comment by BinaryConstruct** [comment]
> While yesterday it was working fine for me, except the bug with placeable items (chests/pylons/etc) today it refuses to open the world I was playing yesterday. That happens both in beta 3 that I used yesterday and in beta 4 I just downloaded.
> 
> ![](https://camo.githubusercontent.com/3c7f8145eab50437ab6f90f327dde9457a58a1e7/68747470733a2f2f692e6779617a6f2e636f6d2f66386462393538323830633131663133393132343738343462386366363332632e706e67)
> This is the error I get and it tells me to upload this.
> [TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4656680/TEditLog.txt)
> 
> That happens with multiple worlds I was able to open and edit yesterday. Ingame I can play fine without any issues and the weird thing is that I changed nothing between my last edit yesterday and trying to open the world today.
> 
> EDIT: That happens when I try to open the world file by double clicking on it (I have .wld ascociated with TEdit. If I open TEdit as admin beforehand and open the world by the menu it works fine. But it still won't open if I double click the world file afterwards. Which is confusing because yesterday it worked and I didn't change anything and it's not the update since it does the same on beta 3 I was running last night.
> 
> TLDR: It works but only if I open a world from TEdit menu, not from launching TEdit for opening .wld files.

That message shows you are using TEdit 3.10.

**Comment by atheran2** [comment]
@BinaryConstruct Now I feel like an idiot. I had ascociated .wld with TEdit before the update so it's probably still linked to that and not the updated version. Still can't understand why it worked yesterday tho', but anyways, it's not a problem with the current version.

**Comment by nosnowowie93347** [comment]
@BinaryConstruct I feel like the remaining issues that need solving are going to be the most complex to solve

**Comment by theoceanmytho** [comment]
I agree, 1200 is imo the only one that truly needs priority, the offset sprites aren't really too offputting, and aside from the pylons, i'm fine with base images

**Comment by IIVII17** [comment]
So I'm not sure what's gone wrong here. I've read the thread and it sounds like the saving issue was fixed by Beta 3, but when I try to load a world file using the latest beta, this error pops up. Additionally, when I do try to load the world file anyway and make changes, none of the changes are saved, and instead it's stuck on "Validating World..." no matter how big or small the changes were. Hoping there's a fix for this.
![TEdit Issue](https://user-images.githubusercontent.com/65681316/82489406-2a53af00-9b14-11ea-90b0-a4547457f597.PNG)

**Comment by theoceanmytho** [comment]
I have no real clue on how to help you, do you use mods?

**Comment by IIVII17** [comment]
I do not, no. The game was made in classic and Hardmode is enabled in the wld file, and as I said I am using the 4.0.0-beta4. Right now I don't know if I'm the only one getting this error and if maybe the problem is with my wld file, or if this is a known issue with beta4. I'll try removing that one hat rack and seeing if that changes anything.

**Comment by IIVII17** [comment]
That was it. One stray hat rack placed in a jungle. Works perfectly fine after I tracked it down and annihilated it for the grief that it's caused me.

**Comment by theoceanmytho** [comment]
@BinaryConstruct Due to the recent bug fix update for terraria, is there any estimated release for an updated Tedit, or is that still unknown? Thanks in advance

**Comment by Alex2490214251** [comment]
The newly released beta 4 cannot function well on my computer. After saving using TEdit for any world, Terraria 1.4 itself cannot load the .wld file. On my computer, TEdit rendered sky (above ground level) as underground, I think it might be the problem.

**Comment by fariasfrancisco** [comment]
![image](https://user-images.githubusercontent.com/11222931/82562074-e8922b00-9b4a-11ea-9f34-1f5f187fa68f.png)

can't load world. Don't know if this helps

**Comment by IIVII17** [comment]
@fariasfrancisco The last hotfix for Terraria (1.4.0.3) which was released today isn't compatible with Beta4 it seems. You can see that the TEdit Max World and Current World don't match from the error. I think that means your world file is currently newer than what Beta4 supports, so you might have to wait for Beta5 to release.

**Comment by theoceanmytho** [comment]
i have the same problem as sky, none of my changes save as well. Beta5 will probably have alot of fixes on it so i patiently wait

**Comment by fariasfrancisco** [comment]
Weird because I created the world when 1.4 rolled out. Or does it get
updated whenever they release a hotfix?

**Comment by BinaryConstruct** [comment]
The world files will always be the format of the game version that last played them. In fact you can even load up extremely old worlds in Terraria and they will instantly be upgraded to whatever game version you have installed.

**Comment by nosnowowie93347** [comment]
@theoceanmytho @IIVII17 yes we do need to wait for Beta5. Beta4 is not compatible with 1.4.0.3

**Comment by IIVII17** [comment]
I can confirm that the Beta5 that was released 2 hours ago works perfectly. Additionally, editing a wold file with TEdit no longer seems to break the pylons. Went in there to check if the world saved (it did), the pylons were perfectly fine (no longer needed to be broken and replaced). Thank you @BinaryConstruct !

**Comment by nosnowowie93347** [comment]
yeah thanks. only a few issues left to fix

**Comment by FlamingSharky** [comment]
Nobody here uses mac for this?

**Comment by theoceanmytho** [comment]
As far as i am aware, no.

**Comment by BinaryConstruct** [comment]
> 
> 
> Nobody here uses mac for this?

Mac support is only available through bootcamp or a VM.

**Comment by tomek-i** [comment]
> The world files will always be the format of the game version that last played them. In fact you can even load up extremely old worlds in Terraria and they will instantly be upgraded to whatever game version you have installed.

Are you referring to the TEdit upgrade of worlds, in my PR I removed this to accomodate for iOS which was not at the same version as the other systems. it should be really optional to upgrade the world file within tedit or leave it as is and let terraria update it :)

**Comment by theoceanmytho** [comment]
I've encountered one of the strangest bugs i've seen amongst the betas, Everytime i save a modification that consists of the world failing to load, thus having to rely on it's backup, but while i was booting up tedit to get a new screenshot so i could demonstrate the changes i would make to explain the bug, i got this message: 
![image](https://user-images.githubusercontent.com/65521684/82621307-c3340a00-9ba8-11ea-8dd9-740c227f3dc5.png) @BinaryConstruct  Apologies for the ping but i don't know whether this is a known bug or not, every change i make such as having an invasion cleared, causes my world on terraria to go to it's backup where it lacks those changes. Thanks in advance.

**Comment by Xanokei** [comment]
Adding or deleting liquids will cause the map to break

**Comment by Sondz1** [comment]
Trying to save a Large Master world after doing any edits would stop on Validating World, even after it runs for up to 10 minutes with seemingly no progression on the bar. Trying to use Save As would give me the same result. Before saving Tedit would warn me that the world had been modified by an external program, despite none running.

**Comment by IIVII17** [comment]
@theoceanmytho I had the same error happen to me on Beta4, and it was because I had a hat rack in place with items in it. After breaking it, it worked fine. I think the same applies for weapon racks and mannequins. I don't know if this has been fixed in Beta5, so maybe try breaking them first?

**Comment by theoceanmytho** [comment]
That might actually be it, I'll make a copy and get rid of the mannequins and check if that works, thanks again.

**Comment by BinaryConstruct** [comment]
Beta6 has a huge amount of changes and some preliminary support for new TileEntities. Hat Racks and Mannequin are probably still broken. Weapon racks, item frames and plates should work.

**Comment by nosnowowie93347** [comment]
@BinaryConstruct dont know if u knew this, but NPC sprites are duplicated. Heres an example:
![image](https://user-images.githubusercontent.com/65568190/82684860-22753700-9c08-11ea-81cb-9fc22f49dc12.png)

**Comment by nosnowowie93347** [comment]
at the bottom of the image, see how the NPC sprites are duplicated? That's my issue

**Comment by NathanAccurso** [comment]
![image](https://user-images.githubusercontent.com/61265573/82716845-760a7380-9c4e-11ea-832e-272eda600247.png)
Still getting this error on beta 6. I had a hat rack but deleted it in TEdit. Forcing the world to load results in a world that can't be loaded in Terraria. Should I delete the hat rack in game and try to load the world again?

**Comment by theoceanmytho** [comment]
Yeah, currently until #1200 is fixed we can't use said described items, you're best bet until the bug is fixed is to delete the hat rack and wait until whenever the patch is released that fixes it

**Comment by BinaryConstruct** [comment]
Today marks the 9 year birthday for TEdit. Hopefully Beta7 will save the worlds and it can become the 4.0 release.

**Comment by atheran2** [comment]
So just to understand. Now pylons won't break? And I can have my items shown in display racks and mannequins, I just can't edit those in TEdit?

**Comment by theoceanmytho** [comment]
so just to verify, beta 7 will work with 1.4.0.4?

**Comment by fakemanoan** [comment]
Still getting "Validating World..." on beta 7 whilst attempting to save. Even if no changes have occurred. World is accessible in latest 1.4.0.4 update.

 It's a large world generated on launch day. Other large world files generated do not have this issue. Attempting to analyse the world instantly crashes the program. If you like i can upload it for you because many seem to have this problem despite the world not being broken.

**Comment by nosnowowie93347** [comment]
This can't be the last release you haven't fixed the sprites for NPCs and 1.4 items @BinaryConstruct

**Comment by nosnowowie93347** [comment]
@BinaryConstruct Tedit beta7 crashes after reading Tally tab. Please fix this

**Comment by BinaryConstruct** [comment]
@fakemanoan Yes, please attach the world file. It should the the version that works in game.

**Comment by OrochiYagami** [comment]
From BETa 2, it is mandatory to have Framework 4.8 installed on the computer ..... But my windows doesn't have NET framework 4.8 ... and I can't install it ... the program only works if you have the framework. ...
How do I make Tedit work without using the 4.8 framework?

**Comment by maxiesnax1** [comment]
I'm using all the up-to-date frameworks and requirements however I've still got the same issue that @NathanAccurso where it will just constantly hang on validating world and saving as in a new directory won't create any files at all.The world is a large expert mode world created on terraria v1.4

**Comment by fakemanoan** [comment]
@BinaryConstruct Here are the files. Removing mannequins and others that people have suggested do not work.
[worlds.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4674094/worlds.zip)

**Comment by BinaryConstruct** [comment]
@fakemanoan @maxiesnax1 Thanks for these world files. I was able to track down the hat rack issue. It should be fixed with beta 8.

**Comment by BinaryConstruct** [comment]
Beta 8 fixes numerous bugs. https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta8

**Comment by weegeesuper** [comment]
i try out this beta tEdit but when i try to start the app, it say tEdit have stopped wroking but when i want to check what is the problem it won't tell me. I try to delete it and redownload it but still won't work

**Comment by Mattbarnhill** [comment]
When I load a 1.4.0.4. map it freezes on Calculating Colors, but when loading a 1.3. map, it will work just fine.

**Comment by CLittleLunaC** [comment]
![image](https://user-images.githubusercontent.com/41792970/82837880-4f7f4f00-9e7f-11ea-9ca3-2e619b1fe505.png)
I cannot see tiles unless I zoom in, doesn't seem to be loading the map view.

**Comment by nosnowowie93347** [comment]
@BinaryConstruct is the duplicated NPC sprite bug finally fixed?

**Comment by nosnowowie93347** [comment]
and the tiles bug

**Comment by BinaryConstruct** [comment]
@nosnowowie93347 which one? Hat racks and mannequin should work now.

**Comment by BinaryConstruct** [comment]
@CLittleLunaC do any other worlds work created with 1.4.0.4? If so please attach the non-working world here https://github.com/TEdit/Terraria-Map-Editor/issues/1244

**Comment by Marakalaid** [comment]
@nosnowowie93347 I'm sure BinaryConstruct is doing the best he can in tracking down and resolving issues. TEdit is an extremely powerful tool; and fixing problems following such a massive game update takes time and a lot of testing. He'll get it done, rest assured.

In the mean time, if you'd like to see progress done faster, stick to providing organized, detailed and constructive feedback; preferably with examples and files of affected worlds.

**Comment by nosnowowie93347** [comment]
yup

**Comment by nosnowowie93347** [comment]
This still occasionally happens, but not a SUPER big deal
![image](https://user-images.githubusercontent.com/65568190/82930878-ec52f280-9f3a-11ea-95cf-5219a2ae4603.png)

**Comment by nosnowowie93347** [comment]
partially duplicated NPC sprites

**Comment by nosnowowie93347** [comment]
@BinaryConstruct  Tedit beta8 crashes after reading Tally tab. Please fix this

**Comment by BinaryConstruct** [comment]
> This still occasionally happens, but not a SUPER big deal
> ![image](https://user-images.githubusercontent.com/65568190/82930878-ec52f280-9f3a-11ea-95cf-5219a2ae4603.png)

Woah...that doesn't look right. Can you attach a world file and give coordinates?

**Comment by BinaryConstruct** [comment]
> @BinaryConstruct Tedit beta8 crashes after reading Tally tab. Please fix this

You can track this issue here: https://github.com/TEdit/Terraria-Map-Editor/issues/1242

**Comment by nosnowowie93347** [comment]
here's the world file with the wierd npc sprite duplication

[Worlds.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4684025/Worlds.zip)
position (3078,258)

**Comment by BinaryConstruct** [comment]
Please try beta 9 for the tally tab and missing Illuminant Paint calculating colors bug.

**Comment by BinaryConstruct** [comment]
https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta9

**Comment by BinaryConstruct** [comment]
> here's the world file with the wierd npc sprite duplication
> 
> [Worlds.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4684025/Worlds.zip)
> position (3078,258)

That is the `NPC sprite frames offset` in the list. I am not having this issue on my machine, is it still present in beta 9?

**Comment by nosnowowie93347** [comment]
imma test that later today
I will let you know

**Comment by nosnowowie93347** [comment]
NPC Duplicate Sprite not fixed
![image](https://user-images.githubusercontent.com/65568190/82944611-5f1a9880-9f50-11ea-8234-d078318980de.png)

@BinaryConstruct

**Comment by nosnowowie93347** [comment]
i think the tally crash is fixed tho

**Comment by andrei9669** [comment]
I also experience NPC duplicate view
![image](https://user-images.githubusercontent.com/31692094/82946776-a3855300-9fa7-11ea-8721-69ed213acb7b.png)

**Comment by millenihilist** [comment]
@BinaryConstruct 

New GitHub user who's not ahead of the etiquette and procedures here, just wanted to ask if anyone else has had issues with clipboard items - such as directly copied objects/structures as well as saved schematics - "losing" items and paint settings alike when reversed on the X axis? 

I planned to include screenshots of Percival91's fantastic Ethnessa village experiencing the issue as an example of what I mean, but I was unsure if some variation of the bug has already been reported and I didn't want to just dive in if there's a proper channel that I'm not using. 

This occurs on new and existing Terraria version 1.4.0.4 worlds and I've experienced the bug through at least beta versions 7-9 of TEdit. Massive kudos for the hard and frequent work on an absurdly helpful project I've benefited from for years now, either way. :)

**Comment by BinaryConstruct** [comment]
> @BinaryConstruct
> 
> New GitHub user who's not ahead of the etiquette and procedures here, just wanted to ask if anyone else has had issues with clipboard items - such as directly copied objects/structures as well as saved schematics - "losing" items and paint settings alike when reversed on the X axis?
> 
> I planned to include screenshots of Percival91's fantastic Ethnessa village experiencing the issue as an example of what I mean, but I was unsure if some variation of the bug has already been reported and I didn't want to just dive in if there's a proper channel that I'm not using.
> 
> This occurs on new and existing Terraria version 1.4.0.4 worlds and I've experienced the bug through at least beta versions 7-9 of TEdit. Massive kudos for the hard and frequent work on an absurdly helpful project I've benefited from for years now, either way. :)

This is a perfect place to ask.

Flipping the clipboard (x or y) removes all sprites (furniture, chests, etc) due to the complexity of flipping the UV coordinates. I created an issue to track this as a new feature https://github.com/TEdit/Terraria-Map-Editor/issues/1247

**Comment by millenihilist** [comment]
> > @BinaryConstruct
> > New GitHub user who's not ahead of the etiquette and procedures here, just wanted to ask if anyone else has had issues with clipboard items - such as directly copied objects/structures as well as saved schematics - "losing" items and paint settings alike when reversed on the X axis?
> > I planned to include screenshots of Percival91's fantastic Ethnessa village experiencing the issue as an example of what I mean, but I was unsure if some variation of the bug has already been reported and I didn't want to just dive in if there's a proper channel that I'm not using.
> > This occurs on new and existing Terraria version 1.4.0.4 worlds and I've experienced the bug through at least beta versions 7-9 of TEdit. Massive kudos for the hard and frequent work on an absurdly helpful project I've benefited from for years now, either way. :)
> 
> This is a perfect place to ask.
> 
> Flipping the clipboard (x or y) removes all sprites (furniture, chests, etc) due to the complexity of flipping the UV coordinates. I created an issue to track this as a new feature #1247

Oh! Now I understand the significance of the work required to make such a feature possible, and no rush on that kind of functionality intended at all. Thanks for connecting the dots for me and, again, for the entirety of the project thus far! :)

**Comment by atheran2** [comment]
On beta 10 my NPC sprites are showing properly on my world. But I still have problem with items. Specifically the boss relics. Only eye of cthulhu shows up in TEdit and that, only the base shows. Not the top. The others are not showing up at all (placed ones I mean). Do I need to replace them or are they still bugged?

**Comment by BinaryConstruct** [comment]
> On beta 10 my NPC sprites are showing properly on my world. But I still have problem with items. Specifically the boss relics. Only eye of cthulhu shows up in TEdit and that, only the base shows. Not the top. The others are not showing up at all (placed ones I mean). Do I need to replace them or are they still bugged?

This is a tedious manual task of finding all the UV coordinates for every single sprite. I added quite a few, but time constraints limited me to calling a lot of them "Unknown".  I would be happy to accept a PR on adding these new sprites.

https://github.com/TEdit/Terraria-Map-Editor/blob/master/src/TEdit/settings.xml#L4395

**Comment by atheran2** [comment]
@BinaryConstruct I'm a 3d guy so the UV in my world is probably something completely different than what you mean. As for the rest I have no idea whatsoever on how to do that but if you or someone else points me to the right direction of how to find those coordinates and what you want me to do on that file, I'll use what little time I have to help you out on this.

PS. Pylons just worked. Didn't need to do anything to fix or reset them.

**Comment by BinaryConstruct** [comment]
> @BinaryConstruct I'm a 3d guy so the UV in my world is probably something completely different than what you mean. As for the rest I have no idea whatsoever on how to do that but if you or someone else points me to the right direction of how to find those coordinates and what you want me to do on that file, I'll use what little time I have to help you out on this.
> 
> PS. Pylons just worked. Didn't need to do anything to fix or reset them.

Here is an older, but accurate description of the UV coords in Terraria https://seancode.com/terrafirma/uvs.html

**Comment by atheran2** [comment]
@BinaryConstruct I'll give it a look today after work. Any quick tips on how I extract the atlas from the game? I imagine for coordinates I use pixels in photoshop, right?

**Comment by MuffinLover69** [comment]
![Terraria_ Error 5_31_2020 5_06_20 AM](https://user-images.githubusercontent.com/66187925/83341411-95636980-a2fc-11ea-9c04-b9f0f10f6441.png)

The world file gets corrupted neither playable by normal or journey character, Tedit Beta 10

**Comment by delaskoff** [comment]
![image](https://user-images.githubusercontent.com/26123204/83354636-a8a92000-a362-11ea-950a-7d87fc1933f3.png)
Cat, Dog and Bunny Sprites duplicating

**Comment by delaskoff** [comment]
Also is it possible to update world somehow to add Journey update content (e.g. antlion lavra, fallen log etc)?

**Comment by BinaryConstruct** [comment]
I think that fallen log and antlion are in the sprite list.

I will look into the cat, dog and bunny sprite offsets.

**Comment by delaskoff** [comment]
But what about enabling natural generation of larva?

**Comment by theoceanmytho** [comment]
You mean the queen bee larva? You can just craft an abeemination for that. Personally i would love to see the ability to change your golf stats for a world.

**Comment by delaskoff** [comment]
@theoceanmytho antlion larva
My world was generated in 2015 and I don't want leave it

**Comment by BinaryConstruct** [comment]
One option is to copy paste sections from a newly generated world into your old world. Make micro-biomes for all the things you need.

**Comment by HedSut00** [comment]
I have the same issue as MuffinLover69. It occurs when i try to load a world in terraria that was modified by Tedit or even just saved without me changing anything. The error was produced by terraria, not Tedit

**Comment by nosnowowie93347** [comment]
@HedSut00 I think i had the same issue as well. That needs to be fixed

**Comment by BinaryConstruct** [comment]
@MuffinLover69 @HedSut00 @nosnowowie93347  Could you please attach the world with the issue here? #1244 Thanks!

**Comment by delaskoff** [comment]
Can't find sandstone furniture at all in Sprites

**Comment by RivenofthreeVoices** [comment]
When I use the Morph tool to Purify the Corruption, it leaves the Corrupted Plants (24) still corrupted. I can't find a fix, but is there a workaround? Perhaps a way to kill all the plants at once so they can regrow to their normal biome? I tried to attach the world but is says that the filetype is not supported.

**Comment by theoceanmytho** [comment]
In terms of plants, your best bet is to go with an eraser tool and erase them all individually.

**Comment by RivenofthreeVoices** [comment]
Is there any easy way cycle between tiles/plants?

**Comment by BinaryConstruct** [comment]
> When I use the Morph tool to Purify the Corruption, it leaves the Corrupted Plants (24) still corrupted. I can't find a fix, but is there a workaround? Perhaps a way to kill all the plants at once so they can regrow to their normal biome? I tried to attach the world but is says that the filetype is not supported.

I created a feature request for this: https://github.com/TEdit/Terraria-Map-Editor/issues/1265

**Comment by FelisImpurrator** [comment]
Is it known that moon options are currently incomplete and only let you choose three moon types? Terraria Map Editor seems to have all nine moons in its options, added recently.

**Comment by BinaryConstruct** [comment]
@FelisImpurrator Could you please open a new feature request for the missing types? I'll get them added for  the next beta.

**Comment by BinaryConstruct** [comment]
A new experimental sprite tool is in beta 13. It should add most, if not all of the missing sprites. They don't have names yet, but they are all there.

**Comment by Tickshift** [comment]
lol ok
![lol ok](https://user-images.githubusercontent.com/66383295/83671883-0031d080-a59b-11ea-9fd8-65b055ac0097.PNG)
(beta 13)
Tried turning off some of the security settings, redownloaded it a few times, tried running it as administrator, looked online, and nothing has worked so far.
Haven't seen this before, so I don't know if it's a problem with my computer or the file, but windows won't let me run it.

**Comment by BinaryConstruct** [comment]
No just a windows and symantec thing. It costs several hundred $$ for a microsoft signed code signing certificate to become a "known" publisher.

**Comment by nosnowowie93347** [comment]
@Tickshift I have the same issue
@BinaryConstruct any way to fix this?

**Comment by BinaryConstruct** [comment]
@nosnowowie93347 @Tickshift I'll look into adding a signing certificate with the next beta. You can clone the code repository, and call `dotnet run` from the src folder if you have the [dotnet sdk](https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.300-windows-x64-installer) installed.

**Comment by BinaryConstruct** [comment]
@nosnowowie93347 @Tickshift Try https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta14 I added a self-generated code signing certificate. I'm not sure if SmartScreen will like it, but it is the best I can do at this point.

**Comment by tomek-i** [comment]
Usually if you click on details it will Make a new button visible and give
you an option to run anyway.

**Comment by BinaryConstruct** [comment]
I added instructions for the corrupt file recovery process:
https://github.com/TEdit/Terraria-Map-Editor/wiki/Corrupted-World-Recovery

**Comment by nosnowowie93347** [comment]
I'll give it a go @BinaryConstruct and if it's a couple hundred dollars, don't worry about it

**Comment by nosnowowie93347** [comment]
Expensive

**Comment by retep998** [comment]
SmartScreen will warn about new unsigned binaries and signed binaries using new self-signed certificates. Once it has seen a given unsigned binary or self-signing certificate enough it will stop warning about it. So while your self-signed certificate right now might still trigger SmartScreen, in the future it will go away.

**Comment by Vehdrehl** [comment]
When I look in the sprites list it starts at #3 (grass flowers) and ends at #469 (table (group 2)). I'm unable to find many items such as pressure plates, heart lanterns and star in a bottle. I've gone through the list manually as well as filtering.

> A new experimental sprite tool is in beta 13. It should add most, if not all of the missing sprites. They don't have names yet, but they are all there.
> 
> ![image](https://user-images.githubusercontent.com/456755/83600836-0e4d0600-a535-11ea-8fca-ba368bf77d8b.png)

**Comment by BinaryConstruct** [comment]
These are styles of existing tiles. I'll work on the filter so it searches styles as well.

**Comment by Tudi20** [comment]
In World Properties under NPC's saved, don't forget to add the Golfer there.

**Comment by nosnowowie93347** [comment]
good point @Tudi20 
Also, I can confirm that Windows Smartscreen will allow me to use the program @BinaryConstruct 
you don't need to spend hundreds of dollars becoming "Signed"

**Comment by FlamingSharky** [comment]
so no mac version or way to use on mac...

**Comment by Tudi20** [comment]
@FlamingSharky Unless [wine](https://www.winehq.org/) works...

**Comment by Vehdrehl** [comment]
> These are styles of existing tiles. I'll work on the filter so it searches styles as well.

Understood, though shouldn't all pressure plates be in the same category? Currently, it only shows the red pressure plate.

**Comment by BinaryConstruct** [comment]
https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta17 Adds some misc improvements to usability.

**Comment by sata700** [comment]
sorry but how can i edit the tally without importing?

**Comment by KorenGan** [comment]
There appears to be some sort of where compiling issue that causes the most current beta TEdit4 beta 23 to be unable to launch by clicking the .exe without additionally clicking on another file named TEdit.exe.config. Clicking on either file by itself will not launch TEdit.
Windows also appears to recognize the app using window compatibility mode using windows 8 as well, and can be configured to launch as expected using compatibility mode.

**Comment by BinaryConstruct** [comment]
The startup time is getting pretty long. I'll see about adding a splash screen.
