### ISSUE TITLE
The Wall Tile selector drop down menu won't sort and normal text input can cause Tedit to Crash.

### ISSUE THREAD

**Issue by nighplasmage** [TEdit/Terraria-Map-Editor#1544]
**Describe the bug**
Failure to sort Wall blocks, and unhandled exception leading to crash.

1. Load Old Map, Start new Map, or just open Tile Replacer plugin.
2. Open Wall block selector drop down menu.
3. Input any text,  Sky,  Sand, Cloud, ect.
4. Observe all options disappear and more lag then with Tile selection, which sorts properly.
5. Exit the drop down menu and open it trying to sort again a second or 4th time as needed.
6. Experience Unhandled exception error prompt, program freezing, and eventual crash to desktop.

**Expected behavior**
Typing S in wall block selection to sort By wall titles that begin with or include S. Editor not to crash.

**Screenshots**
https://imgur.com/a/d8YzHBG
Here you can see code text output after typing in a normal block name,  on next use of this function, the editor will crash.

**Desktop
 Windows 10]
 - Version [Tedit V4.5.1
 - Terraria Version Current Steam release.

**Comment by nighplasmage** [comment]
Issue may be caused by clicking on the selector when it has no wall title available to select. Here is log file of that occurring.

09-09-2021 01:49:27: Error - Object reference not set to an instance of an object.
   at TEdit.UI.Xaml.FilteredComboBox.RevertToPrevious()
   at TEdit.UI.Xaml.FilteredComboBox.OnPreviewLostKeyboardFocus(KeyboardFocusChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
   at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by nighplasmage** [comment]
Typing in stone or Stone, and pressing enter will result in the textbox outputting " TEdit.Terraria.Objects.WallProperty ", again for clarity outputting because of potential code confusion,  TEdit.Terraria.Objects.WallProperty .

Another Crash file related to this issue.

09-09-2021 01:52:52: Starting TEdit 4.5.1.0 
09-09-2021 01:52:52: OS: Microsoft Windows NT 10.0.19043.0 
09-09-2021 01:52:52: OS Name: Microsoft Windows 10 Pro  
09-09-2021 01:52:52: .NET Framework Version: 4.8 or later 
09-09-2021 01:52:53: Terraria v1.4.2.3 
09-09-2021 01:52:53: Terraria Data Path: C:\Users\[user]\Desktop\Skyrim SE\Steam\steamapps\common\Terraria\Content 
09-09-2021 01:52:53: Creating Undo cache: C:\Users\[user]\AppData\Roaming\TEdit\undo\undo_20210909015253 
09-09-2021 01:57:49: Error - Object reference not set to an instance of an object.
   at TEdit.UI.Xaml.FilteredComboBox.RevertToPrevious()
   at TEdit.UI.Xaml.FilteredComboBox.OnPreviewLostKeyboardFocus(KeyboardFocusChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
   at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by BinaryConstruct** [comment]
Thanks for the report, I will work on this for the next update.

**Comment by nighplasmage** [comment]
Will wait patiently, lost 4 hours of measuring and placing ideal blocks 3x in a row.

Tile Blocks can also crash the game due to bad input, but sort properly. It's a new feature this update, maybe not robust enough yet, but it's a very useful feature that tricks me into trying to use it.

If we could search by names and numeric Id, typing 21 shows id numbers 21,121, 210, 211...219, 321 that would also help, but that is just because I like to cross reference natural/unsafe tiles off a searchable list.

**Comment by RussDev7** [comment]
@a1russell I have created a fix for the tile/wall invalid selection crash as I pushed out for 4.5.5-beta, but I'm still working on a method to get the wall selection working. Wall search/filter is still a confirmed bug.

**Comment by a1russell** [comment]
Thank you @RussDev7! You're awesome.

**Comment by BinaryConstruct** [comment]
If this issue is still present in v4.7.1, please reopen this.

**Comment by a1russell** [comment]
This is still present in 4.7.2. The last good version was 4.4.1.
